# Generated by Django 4.2.7 on 2023-11-15 00:34

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "start_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                (
                    "due_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ManyToManyField(
                        related_name="projects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
