# Generated by Django 4.2.7 on 2023-11-16 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_remove_project_is_completed_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="team_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
