# Generated by Django 4.2.7 on 2023-11-15 00:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "start_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                (
                    "due_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ManyToManyField(
                        related_name="tasks", to="projects.project"
                    ),
                ),
            ],
        ),
    ]
