# Generated by Django 4.2.7 on 2023-11-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_project_is_completed_project_status"),
        ("tasks", "0003_remove_task_project_task_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ManyToManyField(
                related_name="tasks", to="projects.project"
            ),
        ),
    ]
